[env]
LIBCLANG_PATH = { value = "/lib/x86_64-linux-gnu", force = false } # led strip in munin requires this....
DEFMT_LOG = "info"

[target.thumbv8m.main-none-eabihf]
rustflags = [
	"-C", "link-arg=--nmagic",
	"-C", "link-arg=-Tlink.x",
	"-C", "link-arg=-Tdefmt.x",
	"-C", "target-cpu=cortex-m33",
]

runner = 'probe-rs run --chip rp235x'

[alias]
build-elara = "build -p elara --target thumbv8m.main-none-eabihf --features=rp2350"
run-elara   = "run -p elara --target thumbv8m.main-none-eabihf --features=rp2350"

build-ejector = "build -p ejector --target thumbv8m.main-none-eabihf --features=rp2350"
run-ejector   = "run -p ejector --target thumbv8m.main-none-eabihf --features=rp2350"