[package]
name = "elara"
version = "0.0.0"
edition = "2024"
build = "build.rs"

[dependencies]
bin-packets = { workspace = true}
heapless = { version = "0.8.0", default-features = false }

[target.'cfg(all(target_arch = "arm", target_os = "none"))'.dependencies]
actuators = { path = "../../../../actuators" }
aether_core = { path = "../../../../aether/crates/aether_core" }
aether_gnc = { path = "../../../../aether-pro/crates/aether_gnc", default-features = false, features = ["no_std", "control"] }
aether_time = { path = "../../../../aether/crates/aether_time" }
bmi323 = { git = "https://github.com/wyatt-mattas/bmi323-rs.git", features = ["sync"] }
bmm350 = { path = "../../../sensors/bmm350-rs", features = ["sync"] }
bincode = { version = "2.0.1", default-features = false, features = ["derive"] }
cortex-m = "0.7.7"
cortex-m-rt = "0.7"
critical-section = "1.2.0"
defmt = "1.0.1"
embedded-hal = "1.0.0"
embedded-hal-compat = "0.13.0"
embedded_hal_0_2 = { package = "embedded-hal", version = "0.2.7" }
fugit = "0.3.7"
nb = "1.1.0"
panic-halt = "0.2"
pulsar = { path = "../../../../pulsar/crates/pulsar", features = ["rp2350", "embedded-hal"] }
pulsar-macros = { path = "../../../../pulsar/crates/pulsar-macros" }
rp235x-hal = { version = "0.4.0", features = ["binary-info", "critical-section-impl", "rt"] }
rtt-target = "0.6.2"

[[bin]]
name = "elara"
path = "src/main.rs"

[build-dependencies]
aether_core = { path = "../../../../aether/crates/aether_core" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"